version: "3.9"
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "8080:8080"
    container_name: rtmp_server
  
  rtmp2:
    build: ./rtmp2
    ports:
      - "1936:1936"
      - "80:80"
    container_name: rtmp_server2
    

  auth:
    build: ./auth
    container_name: auth_server